baseURL = "https://ibm-hackathon-support.github.io/"
languageCode = "en-us"
title = "Hackathon Support"
theme = "ibm-plexus-simple"

[params]
  AuthorName = "Michael Wellner"
  GitHubUser = "cokeSchlumpf"
  Brand = "IBM"
  Subtitle = "Resources for #CodeVsCovid19 Hackathon"

[blackfriday] 
    extensions = ["hardLineBreak"]
